import { App } from 'vue';
declare const _default: {
    install: (app: App, options?: Record<string, any>) => void;
};
export default _default;
export * from "./Base/ElsElem";
export * from "./Base/ElsForm";
export * from "./LowCode/ElsContent";
export * from "./Base/ElsScroll";
export * from "./Animation/ElsAnimationQueue";
export * from "./Animation/ElsPpt";
export * from "./Base/ElsTable";
export * from "./Data/ElsIcon";
export * from "./Data/ElsButton";
export * from "./Base/ElsTableOld";
export * from "./Base/ElsX6";
export * from "./Base/ElsMarkdown";
export * from "./Base/CodeEditor";
export * from "./Base/JsonView";
export * from "./Base/ElsListForm";
export * from "./Base/DialogTable";
export * from "./Base/ModalOk";
export * from "./Data/ElsFormDesign";
export * from "./Base/ElsResizeBox";
export * from "./Base/ElsCron";
export * as ElsUtil from "./utils";
