import { IElsX6 } from "../..";
export type NIFI_CELL_NAME = "processors" | "process-groups" | "input-ports" | "output-ports" | "labels" | "funnels" | "connections" | "templates";
export declare const getCellId: (data: any) => string | undefined;
export declare const getCellName: (data: any) => NIFI_CELL_NAME | undefined;
export declare const getCellNameCn: (data: any) => string;
export declare const getCellType: (data: any) => string | undefined;
export declare const getCellInfo: (data: any) => [name: string | undefined, id: string | undefined];
export declare const getCellUrl: (data: any) => string | undefined;
export declare const getCellMarkup: (d: any) => any;
export declare const statusToStep: (status: string) => IElsX6.CellStep;
export declare const getDefProcessMarkup: (type: string) => any;
export declare const getProcessGroupsCount: (d: any) => any;
